name       : tslib
version    : 1.14
release    : 4
source     :
    - https://github.com/kergoth/tslib/releases/download/1.14/tslib-1.14.tar.xz : 56ce7adfb896442001938470a7f946cc029bfb03ed74e7f62db92d9c9ba83df4
license    : LGPL-2.1
component  : programming.library
summary    : C library for filtering touchscreen events
description: |
    C library for filtering touchscreen events
patterns   :
    - devel : /usr/share/man/man3
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
