name       : tslib
version    : '1.15'
release    : 5
source     :
    - https://github.com/kergoth/tslib/releases/download/1.15/tslib-1.15.tar.xz : 7ce48807cab655076d71a1ceef3ed0ab8a25df98074981d4a8fd1477ee5f710c
license    : LGPL-2.1
component  : programming.library
summary    : C library for filtering touchscreen events
description: |
    C library for filtering touchscreen events
patterns   :
    - devel : /usr/share/man/man3
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
