name       : tslib
version    : 1.12
release    : 2
source     :
    - https://github.com/kergoth/tslib/releases/download/1.12/tslib-1.12.tar.xz : 237f66c9e53789429b1bcc89a36eb7a37f1deb2877e6e7d928e994e3c48d0b83
license    : LGPL-2.1
component  : programming.library
summary    : C library for filtering touchscreen events
description: |
    C library for filtering touchscreen events
patterns   :
    - devel : /usr/share/man/man3
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
