name       : tslib
version    : '1.22'
release    : 8
source     :
    - https://github.com/libts/tslib/releases/download/1.22/tslib-1.22.tar.xz : aaf0aed410a268d7b51385d07fe4d9d64312038e87c447ec8a24c8db0a15617a
license    : LGPL-2.1-or-later
component  : programming.library
summary    : C library for filtering touchscreen events
description: |
    C library for filtering touchscreen events
patterns   :
    - devel : /usr/share/man/man3
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
