name       : tslib
version    : 1.11
release    : 1
source     :
    - https://github.com/kergoth/tslib/releases/download/1.11/tslib-1.11.tar.xz : 90d22b2f1b6dc9899d9491bc0480dfdcb2b55ff6e620ebb999d607aa5389af06
license    : LGPL-2.1
component  : programming.library
summary    : C library for filtering touchscreen events
description: |
    C library for filtering touchscreen events
patterns   :
    - devel: /usr/share/man/man3
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
